image:
  repository: nodered/node-red
  tag: latest

# podAnnotations:
#   secret.reloader.stakater.com/reload: home-assistant-secrets

service:
  main:
    ports:
      http:
        port: 1880

ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      external-dns.home.arpa/enabled: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.raelix.com/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.raelix.com/oauth2/start"
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
      ingress.kubernetes.io/force-ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "1024m"
      nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    hosts:
      - host: &host "nodered.raelix.com"
        paths:
          - path: /
    tls:
      - hosts:
          - *host

persistence:
  data:
    enabled: true
    existingClaim: nodered-data

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

resources:
  requests:
    cpu: 126m
    memory: 411M
  limits:
    memory: 4417M
