apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-controller
resources:
  - ../../../components/ingress-controller

configMapGenerator:
  - name: ingress-controller-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - target:
      kind: HelmRelease
      name: nginx-ingress-controller
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
        - kind: ConfigMap
          name: ingress-controller-values
          valuesKey: values.yaml
