apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: frigate
    meta.helm.sh/release-namespace: home-automation
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  name: frigate-extra
  namespace: home-automation
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: rtmp
    port: 1935
    protocol: TCP
    targetPort: 1935
  - name: webrtcu
    port: 8554
    protocol: TCP
    targetPort: 8554
  - name: webrtcp
    port: 8555
    protocol: TCP
    targetPort: 8555
  selector:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  sessionAffinity: None
  type: ClusterIP
