apiVersion: v1
kind: Secret
metadata:
    name: frigate-rstp-credentials
    namespace: home-automation
data:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:MAolMdNm,iv:vI/USoJTGVvSHE9k2zcABFdpMKBUEZNlC9x9PX0Ouls=,tag:Ev9OFexD9bYEhsUfR5rOLw==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:Dx88w6gH,iv:o4g6y7gLKno1i1KVpzfRKU7sLHtqZHtb/rIazbeAoDg=,tag:t9d/O2s5ksSBKqGzKqTrHA==,type:str]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:TNuWIoABrnMg,iv:2RKuw/1qSLLvhRDvcMTQPRpMgj7sfPqJkBF4fP4Itcg=,tag:MKUkWBRvYXkU2pBn4Nj29Q==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:uFKNMz4misU+BQ==,iv:M8pWMkAO+Mk6EiNuxm9d820A+Q7VXXh2HPYcV67zKQw=,tag:anh22Ylpn/MjmMwZIRO6Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bDVpSjYwVGVURUdKdHVC
            d0ZCbDVBQW9ONkJNMm9iUFVGZ2kwSjY1TWpBCnlIaDZ5NmY3Q0djeUQ3bXF4Z1hC
            dnFsdnl6a0ptcitObmRyaWQyVit0V28KLS0tIGF5QWd5MW5tVFhrZVYvN3lYRWdo
            YTZONElISlZWV2FER2NjSkprMDBKSVUKPHxsOkaWZ7WSpgRlfwZo4wQ9R0KBTZF/
            /biskzC94D4ZOpa1lhacEgOTKS0FBLGpYOVXrVtwyZYIyT7EP1/cYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T17:55:53Z"
    mac: ENC[AES256_GCM,data:dkwbAicoS0Qy5kYB2Fxrbp1g4lEoXKpGJ5zCZoIlEWMUG5vgkY95vEwrmldUDsswdReJ2pqdvNDSeOG2/IJYLZzq2dI5R5VPAkTP+X44PKs4wtxRSDr9XhbltZJ1Kvp8+wPRg6n1g59gKxosDMTX1aDFiQ/oqb1pkmwDgAt6fOw=,iv:Xe52CqMRKfe0i7/TYbXISp90nW0/hO3aAVa8eLUXQrQ=,tag:a/lYixhl+D4Yy5fP6Um8Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
