apiVersion: v1
kind: Secret
metadata:
    name: frigate-rstp-credentials
    namespace: home-automation
type: Opaque
data:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:ERLmjrTp,iv:LfyJHa64/YeuZJPAahzlb+/Va3UoyHR0NP6JuhVEiKs=,tag:KKe298RfsntLRZFFeaNM2w==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:ah2GbqSp,iv:PHG7FhiXwj+ovbuqHs9qslNBcGS6qD1/JE7azPG/fFE=,tag:HEP6HnGCr9UvyHfPlbL67A==,type:str]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:7ggph/p2YQp2,iv:0Uq4eBCBMakL0XWu+ch02X96dB52JwGLos4Dodv2374=,tag:I0y1eO3Tz1co5jS5hIwW+w==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:Zqroa2QBB2Ihow==,iv:J5bmtBBS1x42l9CEft0zrUIvjFcGdg1xH5WQOWM3FSk=,tag:ilKssIR+qew/yjflVTTNuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNzM1T2JOb0VVbTVXWlJl
            YmxUdzlWaXN3amlodmp6VFpEMG0rNGNvWWtRCmVlcXlIYmxwL3MyQjdtaU1FZWFU
            QUJveTFYRmxoTW12amtqbC8vNjRrWDgKLS0tIEdZbC8rNzN4RXFjREJ4NUdFK1Zu
            SVFSWFhjeUdqSFNXQVk0QTJQaVFHdFEKRCYma7eo8sBpGYMBBKochf20wlBEOygJ
            1HIgOMgNwDhfX/S+rMJ44at7PwtltDo8/hVsE+SLRzgkzqr7HACqkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T17:46:04Z"
    mac: ENC[AES256_GCM,data:P4bzBIHi0u93W9Ah/wtK+ALVtL0vSeaIj7WQf96kT1HR+mz2BEmx8joFd3uD+yUhLfVETPWpd9VDptkL2Cf/O/FPhvOJzYudEFuChi/bhn8gi4wcoMFagSBod+Cm1XLDm/TlRUbefODTDJgep/cM+6Ke9MET3qyeCHaFgKL20kU=,iv:1e4ufqhq/umnCoDhYARIjcP65s723D7v87pQ+kICVrc=,tag:fX8vESDhbf65kSVP0Q6tkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
