apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: frigate
    meta.helm.sh/release-namespace: home-automation
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  name: frigate-extra
  namespace: home-automation
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8554
    protocol: TCP
    targetPort: http
  - name: http
    port: 8555
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  sessionAffinity: None
  type: ClusterIP
