apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-default-login-rb
  namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-default-login-role
subjects:
- kind: ServiceAccount
  name: user-default-login
  namespace: argo-workflows
