apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-default-login
  namespace: argo-workflows
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
