apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-initdb
    namespace: data-process
data:
    initdb-script.sql: |
        create user bn_keycloak with password 'postgres';
        create database bitnami_keycloak;
        grant all privileges on database bitnami_keycloak to bn_keycloak;
        create schema if not exists keycloak authorization bn_keycloak;