apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-initdb
    namespace: data-process
data:
    initdb-script.sql: |
        create user bn_keycloak with password='password';
        create database bitnami_keycloak;
        grant all privileges on bitnami_keycloak to bn_keycloak;