apiVersion: v1
data:
    scrape-config: ENC[AES256_GCM,data:FTj46iIM5YovveMoqRxVPyw6c4uH3x8ftifF1gvtRXZDThKDXOc/DgUNI+yKSHDCY/bjBPfV7TL4w66EiCv+dgnsXXmZOqMnXcBCopyv3lJHQz14D8bP1kaHEm8RfnituohFtSpBWei/0ALTzyfKeReNK6fL3PgS8bd+hQmrN+ICs0sUa37gT+oKXy5IrArldbcLRMtjinrRg+DdelF+dFY5ajsKCwcE3gB3MJtAE2VbGbPZTmnKOn3/ckQy368fZXivNo5q/6xz9h0GE4eNrE285jaKBIyd4ox2BBX4Pn3whOwWCiWHOjhdbbHpD7mAdvgykhnEbgaf/MG9TZ8NNyyJo76esaohthGNiyBywDTESS0/jE++v9ysLJxwWr4eYtpIT4TvIt1uNnxXXNtXHT528KtJODh/Ss/TKDOidXbGZYcFOOqJ+JuggoYz6en5BFfuAGUJMq4wfGaz4iX3fe4Ifbs78OZrQbpX1qIRmLPZEb5N3xOnkJ/NnipoSEG6AF/oQwKomruQuoGnNW6AVAj+qQiYP4WrQC6YmGnv9oH+EmFBweqcWFdTsMcXM69UbK4z/uCEodv1unAmaJ7A2FBLVgeYejtXdo8Yr3buD80uF1bVaBR+1ME+9YTFA6K8F1spNKVT6QR9Vf3up8IvAZtgIW4fUoiZ5E1ksumh3xtl3UqQIkYtDCO2rgiDuL64y7QAMsrEtixvX3CUIcsYuA==,iv:n7vG2naESGoKLi46XDBLHytJBJD/HdH0qRs4B+cgD8U=,tag:s3VMUA9ZJA+gs1r5R/dHXg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: scrape-config
    namespace: observability
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elje5gj3cyqhn44m66xlngczm8dklwmry9803ne69945e256xgequ9xtt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSGhMT0FTSXhKK2phRlNJ
            VzR2VG9DZjcxbk9BQk9hMm5IVlhnTUgrSFJJCnFWc3FCMnRRWFBzaTR2L0hyMFNZ
            SGpRbTFWZzBsZVJhdFFBdUhBMTVoeTgKLS0tIFMvWFR3MDlnS3ZVeEdFbmhIZ29Q
            cXIwNmpVaDdGYVJ1MFd0Y1M1bG44Y0EKmSMQQlk58GlaZSmfWFC6W5LtfKbcRYvr
            9i/AYk2uFZa2c+vdyMlvQ0dwb2+QtEHyIxdk/XuhdF56J8b2RvfeLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T22:28:53Z"
    mac: ENC[AES256_GCM,data:avTTe5SEH2mTb5QHdbqwI5QwgaNRCx3jdXBhosGnsc4fsqEJTrY0qW4ziB1oBxlL7vWOk7uK+m7GWAlvnEoX+pnnmzsTNLVxM41FKL1P9Vivzv1V8ki/doqo5QIhN5RitKunjCrxrrpDLr7NFwZJFDdpitd4198hXN0YhIuhhvY=,iv:+HZqspU9pDbuKBLXzKVwX6/GLjlL/0R0Y4VNFePyLOU=,tag:FAnZySNdmXdTv6YVDrfloA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
