grafana:
  enabled: true
  adminPassword: prom-operator
  persistence:
    type: pvc
    storageClassName: local-path
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

  extraConfigmapMounts:
  - name: auth-generic-oauth-secret-mount
    configMap: auth-generic-oauth-secret
    # defaultMode: 0440
    mountPath: /etc/secrets/auth_generic_oauth
    readOnly: true

  grafana.ini:
    server:
      root_url: https://grafana.raelix.com
      # serve_from_sub_path: "true"
    auth.basic:
      enabled: true
    auth:
      disable_login_form: false
    auth.generic_oauth:
      enabled: true
      client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
      name: Keycloak
      allow_sign_up: true
      scopes: profile,email,groups
      auth_url: https://auth.raelix.com/realms/master/protocol/openid-connect/auth
      token_url: https://auth.raelix.com/realms/master/protocol/openid-connect/token
      api_url: https://auth.raelix.com/realms/master/protocol/openid-connect/userinfo
      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
    - hosts:
      - grafana.raelix.com
    hosts:
      - grafana.raelix.com
    path: /

  # dashboardProviders:
  #   dashboardproviders.yaml:
  #     apiVersion: 1
  #     providers:
  #     - name: 'homeassistant'
  #       orgId: 1
  #       folder: 'Home Assistant Dashboard'
  #       type: file
  #       disableDeletion: true
  #       editable: true
  #       options:
  #         path: /tmp/dashboards/homeassistant
  #     - name: 'opensea-dashboard'
  #       orgId: 1
  #       folder: 'Opensea Dashboard'
  #       type: file
  #       disableDeletion: true
  #       editable: true
  #       options:
  #         path: /tmp/dashboards/opensea-dashboard
  #     - name: 'logging-dashboard'
  #       orgId: 1
  #       folder: 'Home Assistant Dashboard'
  #       type: file
  #       disableDeletion: true
  #       editable: true
  #       options:
  #         path: /tmp/dashboards/logging-dashboard

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
      # - name: Loki
      #   type: loki
      #   uid: loki
      #   url: http://loki.logging.svc:3100
      #   access: proxy

  # sidecar:
  #   dashboards:
  #     enabled: true
  #     label: grafana_dashboard
  #     labelValue: "1"
  #     defaultFolderName: general
  #     folder: /tmp/dashboards

  service:
    portName: http-web
    type: ClusterIP

prometheus:
  prometheusSpec:
    storageSpec:
     volumeClaimTemplate:
       spec:
         storageClassName: local-path
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 5Gi
