apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-json-exporter
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-json-exporter
      version: "0.13.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 6h
  # values:
  #   installCRDs: true
  # valuesFrom:
  # - kind: ConfigMap
  #   name: cert-values
