apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    apiToken: ENC[AES256_GCM,data:NkIiQJQIkRZ6fL2Jn0JiKDrrKdIWo5b4MtcCkHyKVz0wridpYEIn9/9IaCen4CbUUoRu3NRFatY=,iv:GbLEE+yCS0j5h/m3YSxWwT6MbTyFFQTEtbwslNF3N0c=,tag:lyYH7DVrCVjl0f5VxXytnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8zks0v22svnqevhtu4y8jynnhkhram08lyaewd45hhy864kjaxqma9fw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMME9UTUdSbGxCZlJaenRP
            LzU5VXY5Tm45eHRtcklqK0lKR0hDUFB2T3dZClR3TmVHSUgxNW9UZWlrZ1pRbG1C
            c214bE1DWHhNaHZKM3ZBL3R0Zk9nTE0KLS0tIFc4SEZIelJ2QWFJYjZIRUNIeHBs
            SU0ydk5TNDRJMmhrbndYaU1pYkI3NnMKHiQs/wrBky/u19s5WaFogKZ7JFhOIEhS
            GlOZfkM143HOLOu2HjYxP0LauyNhoSryKyXbTBokQ10+7QwB7lagww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-12T15:32:57Z"
    mac: ENC[AES256_GCM,data:evRtBg9plgjY/mWQ2yYRKvmq+XEvO5pwAC3LydqFyC1wzeJOysiARGUvLgfzRhxYSF4C77u6S9gd0Jsl4tztToj+4fURetwAwlnE0Hj/xjYyWYGEU/5zueoorx8hn2hOyCaFC6mMVTeVoarh7Fu7VkWoVkU3wYam8/oJQictiDo=,iv:U6jterZeRlXy3C67R9NWvqBdfa2AyYqaabpB/+apXMQ=,tag:f5ZnK07yLFJJB9n3g9UoEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
