apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    apiToken: ENC[AES256_GCM,data:eMNkObUGnvXQI6TqeCWFKomfJ81eIpQ802U0ue9foWalozUSKeSVr6gIF1FqnsFcW4VFfo3KwOI=,iv:xxbzAkA1HtHqQh2ErPHXqi4TVoyRpUB00hG/DWoZJ1E=,tag:4dQp7kpOmNqDwKv4t+Tf6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8zks0v22svnqevhtu4y8jynnhkhram08lyaewd45hhy864kjaxqma9fw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVjBIME9kcnh0K2MzZjht
            c01LM1Irc2pGSzNpMkRiWXBKaU1sbWRuVkg4CnBOL1ZCTDAvK2NzUFBKbmZCMmdL
            VG5hRUU3dXlCZW9zNVcwdjZxdkoxNDAKLS0tIE52d2I2b0M1MlRTQlNUckZ4Sk1a
            N1lVc29BQjFSYnFKd3lJUVhNWGFEM00K4rvenUxc9zNt2lzI7Y+DGeWucML2meDm
            B4TXPkVHLRh42tG/xm9EVXWbDk+2XQ3uGzaKaGoCjdh+TfRplwwSTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-13T07:53:17Z"
    mac: ENC[AES256_GCM,data:mdnIjdmmrnxxwgShphR0N2bmrn4JY+ep3tYDiKFa74bbm2nTgpDb3IV7MJidztWmUQEFJ0qmoVPV5pp2oYuXVkBWj/bGVJj9/tIrXLQ6SgILt2lCC3ioY8Zedt0eHdNKICNqbnSteXuggEr9jKjjtPBHP/Z4DzBBUpIGxfvtLGU=,iv:HGy0POyecAM0Tz2JNYf7yCF4AsgSnS3GoPOgYzsBx2U=,tag:e5wv+30/koCC4y+cp7aWIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
