apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  dnsNames:
    - "*.petruz-central.it"
  secretName: wildcard-cert
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
