apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: music-assistant-server-app
  namespace: flux-system
spec:
  dependsOn:
    - name: home-assistant-app
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/central/music-assistant-server/app
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
