apiVersion: v1
kind: Secret
metadata:
    name: mqtt-users
data:
    users.json: ENC[AES256_GCM,data:M6kiVJ1KRbvvLzpiNAHE3lyJE5IjjyLI0Pf9SJqsNvPAPxUlo/6e3KiyQO1YoQDxh9x2XElwmCturA4gt1XbUvuEbtKpGMdbjc6xLCBF+UqMNiqQEM8y5eLXfPWw7bFQ,iv:vRxOEfP/zxx3ZwQI2kkVbAGQmvnIev036goEWqPAT9g=,tag:FiiryamIYhKdPJPAoI7lUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snagr25j2afgqkltfwhkuv453w2rgnlykf7k5rczk0ml03vd4fzq2mga73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUGlKTEpuT2VCSW90OWhj
            bjBBcFQ2RWxPS0RSZFVkeFpqcGtwbk1TTVFjCjNzSW96MUd2aVN0bE11Tmt1YkFF
            ZDJ4SWxTdVI4V2ZtSy8yamZEMnU2N3MKLS0tIEpuaktvM0ZhOEFmR2FiaU5QekNa
            ZmFMZnNzZnphUGR5TUxIMTRhdjFXQmcK41B22eWuxkcq1ov7PUGC3gPfFUsskTRP
            ithUMdp6rNT8JdGYYPiS6xgVD+uiwAcZ671MlqVqYO32pUbRXrhq0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T19:10:29Z"
    mac: ENC[AES256_GCM,data:WY9X0DKorlUYH6SBzG/ZmvpAItIwDXWNxf3YavZl0CQ5AB52tahD6omIKzw9t48cJPncPZYgnuXcPydPKOKWPMxvclg9g6jdwvympm94Hez8sxcWQ3ubzNKJuY1tsVyJIFeYBDeKbC0/uJpzW5Tu3bkNWBf8ImuMFeN/CG9WBXo=,iv:3Fz+WFyHRgxKLuIxKF0kHkCChauTEggDE7C6zAK5UDU=,tag:3dOSxDPXqKEvCVkVrdEClw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1