apiVersion: v1
kind: Secret
metadata:
    name: mqtt-users
data:
    users.json: ENC[AES256_GCM,data:t1b8OrXl97eK7OXgjpH1AU71C8185EqqnBfA0DJudtdFmuDp3VewDVTw06cO1QgU0ihP83kmFo4ousjskVwOueWnXcVDXWnd4977FNp245dUn4EVLoaTFaXC66fEVI0hxwaXztUSpZb0wxsCF9EOKw==,iv:q/kENwCXJzGL6OBW+oIo8634n5SSCOllS9ftDezzYjw=,tag:TDqLDYS3m8PaQ9/Gzk3fFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snagr25j2afgqkltfwhkuv453w2rgnlykf7k5rczk0ml03vd4fzq2mga73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYnM3dXl1N0ZUUDF1S2pM
            Q1k0R1FKOENxWlBGb0xYREdxSlBBelIzaUJzCk82NXJWbDRadGNIc3dzUklnbk1u
            RzFKMit4UzVzbC9lYXlPQUtyYW5RSTgKLS0tIDM2RTREb0ZOTlI0MUFPaFBmNTNI
            NFRqL3RYK0xUWGpwNHY3QW5ZQU1kV0EKd3YqIHZyRrjprhTHrRVG0ytHAm5934Gd
            9jz9G2hscFCcn1e9rDzP4JRlEbkm+cRt7j5rkdbeQVmKio3sQMRODw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T12:58:39Z"
    mac: ENC[AES256_GCM,data:H3MZd7RdROFNxSH3qBfZy10DXZTi9sokZECYEykmVxlTkUkdD+6KYl5zQnzRQX7nthJGSAauG8z+UWSn8Hoh41TNHiC825w4agxK67I97oFJDajJYUBA1jw3VfP0M9r82McNOwZP3l8ep/h97HTA4LLjDtfOiP2Cjq3IMJUy1ZI=,iv:5GWbopq8xoEkL7iTD49lQa/DpuHFqjsxBi2QtWXDZao=,tag:cxkRpC2H+Uw33brjECN86Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
