apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:7qAjZkpXJoJmhbQBOD4wew==,iv:yGm8cYEBG+TNbrXuzFQbo+huhsABkexTFJTEHZlFLNk=,tag:HoQEOmmt2mPYgjZKeMiBbg==,type:str]
    client-secret: ENC[AES256_GCM,data:Aj2T0eQI4UZtAdU4gLIvnQ==,iv:XVhFIqdjhOhJyIjFg1XzqaLj+g9okzCAUBXPsSfiVxk=,tag:HrtIDeGLYShlHbV0Lfw3uw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:vvWxizUzEEHwBVRiX7IEDHYF1U+HkyBe2Oi5vpX5eGFnGQ9SXu2K+r+2Kbnd9jk3yL5skZCggbOSuG+X,iv:08HJLrhrjqjCkfZlrYF1deaIEH6SeQdgP1KlMvY0icw=,tag:XKV4c7vw0mFBymPIrtD+7A==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: oauth2-proxy
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8zks0v22svnqevhtu4y8jynnhkhram08lyaewd45hhy864kjaxqma9fw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUHJrN1A5bDJKTmN6N0VO
            ZTRJaWY2d29tRjZLR0M0dTdpMjJrZ0IvSFZFCnNDaVQ4KzMvSk03NmoreWQzeXNB
            MDltMTRBRkRxd2lrSlVYVnFmSkRQcncKLS0tIEJTd1BkTHBMenpyU3FpamNTVlVB
            SlkyeXNua0RucmN6dGtmdUZqVUlYSk0K76fBY7FtLBYhC+xLKqdizs1duJJStuVk
            PotqCnyRP2AyjpUDRO6hqHZq5RgSFucsRIRKaAV78GoyYjFIA42F+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T07:31:30Z"
    mac: ENC[AES256_GCM,data:PXlU+dqHlG6wA+h2AJmlFkLP8unMD8JJVqF2q+tDCzJxjuflWVzt6/digRhzBt1suSUmLEqUWFxcKur6j8vzRtbmsjpa1JGg4BYSnt17l207Iixik4zayPjgRyRoJa+qUKxOGxfx8ARQsJtbdXP4KQY5ACR4965v9Wlu8XO45vM=,iv:UnNMlWEfb/dCV9FBh/GQJD+AGFhS+Wj78iK+KtMVGoI=,tag:kVS5912vc6NJQBO/Z5hO5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
