apiVersion: v1
kind: Secret
metadata:
    name: frigate-rstp-credentials
    namespace: home-automation
data:
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:h8exYEPAAXLxk8zL,iv:SN0T34Av6Y2jusrv/0qut7DLSF1BgMwdyasBg3kMetI=,tag:+qy4cQ6JdgtGyTi1g+H9iw==,type:str]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:MW+CvgB6/sDZYJL8rjPXtQ==,iv:6u1OB1cQuvd7+jJBdx9FUWFIHxTNBI0yClvFSZJY/5o=,tag:GQhMrMZrSZqGz2z7O1QA7w==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:p/CvvoOeJUe+XqrG,iv:O+/YgEg9oCZRZ8tdwFjRoVh7oYNtw9enSU+O/1g3v6w=,tag:ij9mkNI20+qF3gQEcKHr0Q==,type:str]
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:5wW+BWh9vYxFCvVLOsBb9A==,iv:5OfmjzoxupWQrIteXcGsGVzYiA1R46L0K2I8caenicQ=,tag:9R0Sw7C7no2p5EWa+kr34Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snagr25j2afgqkltfwhkuv453w2rgnlykf7k5rczk0ml03vd4fzq2mga73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1hvWHMybmRsTzh6UEJB
            K2FsNnhTaUpmY1o5dmlYZnFiYktVV2YrVDBNCkxUMUk2Wjc4cHJJSlBHUU5PSXhD
            OUpCM25rdU90b2dWNzVWVmU1Q1VVNWMKLS0tIHoxT0hDQ1VoZEREMkJHSUFTd001
            bm5DVFZ6SlBoTGorUUk3Z3NoWEhKTTgKuVyrajqkuGMZGHA5358TwUB3raxBxWN4
            5sKco0P/SHuYSysEU0lbUD/lvgNY6bzct5dnxa9UNQlxU6FlEolADQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T17:45:37Z"
    mac: ENC[AES256_GCM,data:7I0Ncq/mfavvRMK93Pr/4CliMTVnfj3VJ4hcAwEmT93emXZCeaiUurMbYzt1muRc1cpLnt4GAoSNv8OsShzh18VxxMbYi/0bP+bav6HLQQglYIepm0bTYyZbCLLul2q7qDlvd495PRL7hFtlQn9VekVCQ07JZ2lhThrsLAyk6xI=,iv:asl8SHVnJQwC01Fpxys0u16ElEvQkBf5IKINfVbJve4=,tag:ixojmpjoqybX3tmQ0+JSRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
