apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: joplin
  namespace: hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: qjoly
        namespace: flux-system