apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: double-take-data
  namespace: home-automation
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

  # storageClassName: ceph-block
