apiVersion: v1
data:
  scrape-config: LSBqb2JfbmFtZTogJ2hvbWVhc3Npc3RhbnQnCiAgbWV0cmljc19wYXRoOiAvYXBpL3Byb21ldGhldXMKICBzY3JhcGVfaW50ZXJ2YWw6IDYwcwogIGhvbm9yX2xhYmVsczogdHJ1ZQogIHN0YXRpY19jb25maWdzOgogICAgLSB0YXJnZXRzOiBbJ2hvbWUtYXNzaXN0YW50LmhvbWUtYXV0b21hdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo4MTIzJ10KICBzY2hlbWU6IGh0dHAKICBiZWFyZXJfdG9rZW46ICJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcGMzTWlPaUptTXpoaU1EbGtZbUl6TTJNME9HUmhZalk1WVdVeU1tUmlZemN6TURsaU55SXNJbWxoZENJNk1UY3pOREk0TURZMk1pd2laWGh3SWpveU1EUTVOalF3TmpZeWZRLnFvTTkxWFhJTFJfVHVuTzZmNWUxOF9kWEp3aGY0UGZvR2Y4NEhxVnMzLVkiCg==
kind: Secret
metadata:
  name: scrape-config
  namespace: observability  