apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-nfs-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # NFS supporta accessi multipli in lettura/scrittura
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.15.22  # Inserisci l'IP del tuo Synology NAS
    path: "/volume1/music"  # Percorso della condivisione NFS sul Synology

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs