
service:
  main:
    ports:
      http:
        port: 8095

ingress:
  main:
    enabled: true
    annotations:
      auth.home.arpa/enabled: "true"
    hosts:
      - host: &host "music.petruz-central.it"
        paths:
          - path: /
    tls:
      - hosts:
          - *host