
service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8095

ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      external-dns.home.arpa/enabled: "true"
    hosts:
      - host: &host "ms.petruz-central.it"
        paths:
          - path: /
    tls:
      - hosts:
          - *host

