{
 "title": "Pannelli",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Energia prodotta",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.zm1es060m3p387_generating_power\"}",
     "legendFormat": "Energia generata"
    }
   ]
  },
  {
   "title": "Consumi attuale",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.zm1es060m3p387_consuming_power\"}",
     "legendFormat": "Rete"
    }
   ]
  },
  {
   "title": "Consumi attuale rete",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.zm1es060m3p387_importing_power\"}",
     "legendFormat": "Rete"
    }
   ]
  },
  {
   "title": "Batteria Pannelli",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.zm1es060m3p387_battery\"}",
     "legendFormat": "Percentuale"
    }
   ]
  },
  {
   "title": "Carica batteria",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.zm1es060m3p387_battery\"}",
     "legendFormat": "percent"
    }
   ]
  },
  {
   "title": "Energia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{entity=~\"sensor.zm1es060m3p387_today_generated_energy|sensor.zm1es060m3p387_today_charging_energy|sensor.zm1es060m3p387_today_consumed_energy|sensor.zm1es060m3p387_today_importing_energy|sensor.zm1es060m3p387_today_exporting_energy|sensor.zm1es060m3p387_today_discharging_energy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energia",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{entity=~\"sensor.zm1es060m3p387_today_generated_energy|sensor.zm1es060m3p387_today_charging_energy|sensor.zm1es060m3p387_today_consumed_energy|sensor.zm1es060m3p387_today_importing_energy|sensor.zm1es060m3p387_today_exporting_energy|sensor.zm1es060m3p387_today_discharging_energy\"} offset -5m",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Consumi giornalieri",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "last_over_time(\n  homeassistant_sensor_energy_kwh{entity=\"sensor.zm1es060m3p387_today_importing_energy\"}[1d] offset -1d\n)\n",
     "legendFormat": "Consumi"
    }
   ]
  },
  {
   "title": "Instant Power",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=~\"sensor.zm1es060m3p387_exporting_power|sensor.zm1es060m3p387_generating_power|sensor.zm1es060m3p387_consuming_power|sensor.zm1es060m3p387_charging_power|sensor.zm1es060m3p387_discharging_power\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}