apiVersion: v1
data:
    rclone.conf: ENC[AES256_GCM,data:BN09qIiCzZXvmnhsmspjeqY2OylLaVSxq+D4VFmdKcGQd5Dhl3X0HBTWEQcnH5Oyd27UMopLcXaC4XeElkMKhLdU0v+7hQaL0exnbthBEKVfZHeQGozh0jmRq1RiecsJzW7y4TFH9JkH6uoeYSW/5lpJ9jJtMgz0hJEGmBmKOvCYFg1uzxau5FcWlBBmvTxBlFFZPHqTdOTmmKXpJOcl8jrTNVx+kqg57AKzIzYpneFViHLmNGoMCQXKK2aKSEZUIMACTERjcq3nMyNw+Ztgyg+z1MZf3Xzs17HuUIkkxdTMv13JJlHkLlIhlxJpfXWIp50EGe8IshMLC/TcWc1WfNCSW3EFVL2BXNqOcPsIXCeNkrhg0+IEwG+E0OByRU7gPO4tZGkPqc0N5ED63RRtZoSQYr7dmRCImCZU6Qyb1DgyJEJC0h00Gf6aKUVQwCIHONlgipjbOvWmdDAzcwnUnJRHf+1FBbhiICSr1hMmrE7Pc00xvdFRUNWIKJMKtTORHCxkmTMHoGRhlOeqZNsnQlFd8NG657AM9ETiANJtERDgaKRl5oEvcROzZvsZ3veSb68kBQ5PPKDwgw0XbKeSPpj0PBqgUTr/0vLCt5dOfOUT/SAjoIcH9gjicJK5fiXcFrLQfoJXcXuI5/3qBb6drSArZ9oAZhe2F6ZfLJZFimv/wIC1P0LQ0nqMtgB+qjrT8iWeyhK2KD40oqhwff0hoqIEeWsHMsBCT3uryqfAyC3d+9nD97Gd8Nesg/l+sJxwdrC3j1fH/+KOwI1blkY3Fq14WtvGIXynguR+BMzU26u/0fNnOa/YpOjpQrIsczf7gxuVfmZxJXxd0CJVZjCubAgc33CQIkhw4685/2gkVyne/l0vibjLKQ6uFjRxnaYMlxFhaIRZRJtni5WQb1axeG3SiU8YkoBbbUh3jo7Oe9CZQ4dV65xOmw4754JPpmXQlL8yexjbnbZjWZOS/uWabJQnz3jMjJLpbK/9JlADnr5b+kcT/8+rgumYowko5WuNYrKOjxf1E2FmCt1+av/Ga/zUcfZS3hqLxLW5izpk/GC86bXTu7y+k3us8kDHt5VJab4zowa9AgI=,iv:a1ZDibwjwQm7kq2sXYf4FJYkiLnOGv+f/PynL/+Xyo4=,tag:7OoO2N5xTvcNFsMAo5Ql4w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rclone-secret
    namespace: hosted
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a8zks0v22svnqevhtu4y8jynnhkhram08lyaewd45hhy864kjaxqma9fw9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZEEvSzVwYTFCRGxrMWNn
            cnpFcE1Hblowd3dQeWJSZ1BhbjU3S3lWZWcwCkxGSG1zN2d1bncrWTBrK1VVd1pq
            WlBjU3pUbjlZVHRiLzFLWUVHS09vWTgKLS0tIEQrQm9UeENIc0w1NjYyYTVUK01G
            WjIzdVpGaHErTWdlNGF3WlVwZnNkT0kKUjtAcJfBLRZakvncOFEQDsdm5Iy4qJUY
            N+oGWGpFeCHFnu1ikm7FxGvzWEKtqIbFkGpTVjmyq2wLB8qJ4/m9DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T18:00:48Z"
    mac: ENC[AES256_GCM,data:ROC2rUUTNsxA1+NLwwWBGBSuIYGzgB6XKxI48tIp7SBVIIEkyAVk+sY2yoNCfMEqeIbafhTQ9ktl4F1Ub529j6L4lCMo41WPQPVKFPNlQfGtxbNHLpbCAj5sKuJ+65kOV+4Hn7zCWnmRIXvHs7o5hPRRVzxEFsQCh4101R5kDkI=,iv:PP/CKibIPYNApm4dgzcJEN9CCpG4wff4nwoMf0hyyFs=,tag:RT9wtdgFSxz8eAumnZ21jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
